# Generated by Django 6.0.3 on 2026-06-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_seed_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carcolor',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
