# Generated by Django 6.0.3 on 2026-04-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_brand_color_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Odometer reading for display/optional tracking only. Do not use for maintenance reminders—use date-based reminders instead.'),
        ),
    ]
