deploy-dev:
  stage: deploy
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
    IMAGE_NAME: "carnova-backend:latest"

  only:
    - dev

  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - if [ -z "$SERVER_IP" ]; then echo "SERVER_IP is missing"; exit 1; fi
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    # 1. Build Django Backend Docker image
    - echo "Building the Django Docker image..."
    - docker build -t $IMAGE_NAME .

    # 2. Preparation on Remote Server
    - echo "Preparing directories and environment file on the server..."
    - ssh $SERVER_USER@$SERVER_IP "mkdir -p ~/carnova"

    # تنظيف وتجهيز ملف الـ .env بشكل مباشر ومضمون
    - echo "$ENV_FILE_CONTENT" > .env
    - sed -i 's/DB_PORT=5435/DB_PORT=5432/g' .env
    - echo "WEB_HOST_PORT=5004" >> .env
    - echo "DB_HOST_PORT=5435" >> .env
    - scp .env $SERVER_USER@$SERVER_IP:~/carnova/.env

    # 3. Transfer docker-compose.yml to the server
    - echo "Transferring docker-compose.yml..."
    - scp docker-compose.yml $SERVER_USER@$SERVER_IP:~/carnova/docker-compose.yml

    # 4. Deploy and wait for Database to ensure Django won't crash
    - echo "Transferring image and deploying via docker-compose..."
    - |
      docker save $IMAGE_NAME | gzip | ssh $SERVER_USER@$SERVER_IP "
        gunzip | docker load &&
        cd ~/carnova &&
        docker compose down || true &&
        
        # تشغيل قاعدة البيانات أولاً وانتظارها 5 ثوانٍ حتى تستقر
        WEB_HOST_PORT=5004 DB_HOST_PORT=5435 docker compose up -d db &&
        sleep 5 &&
        
        # تشغيل الـ backend الآن بأمان
        WEB_HOST_PORT=5004 DB_HOST_PORT=5435 docker compose up -d backend
      "
